title: Nico CSSE Project 
description: "Class of 2025"
owner_name: Nico Orozco
github_username: lowmonkey4586
github_repo: "Nico_2025" 
baseurl: "/Nico_2025"
future: true
remote_theme: jekyll/cayman
minima:
  skin: darklight
  social_links:
    - { platform: github, user_url: "https://github.com/nighthawkcoders"}
    - { platform: x, user_url: "https://x.com/NighthawkCoding/" }
    - { platform: youtube, user_url: "https://www.youtube.com/@nighthawkcodingsociety2868" } 
# remote_theme: pages-themes/midnight@v0.2.0
remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
  - jekyll-remote-theme
header_pages:
  - navigation/blog.md
  - navigation/search.md
  - navigation/about.md
  - README4YML.md
  - navigation/rpg.html
  - navigation/adventureGame.md
  - platformer.html